### ISSUE TITLE
Expose deploy hooks for web services

### ISSUE THREAD

**Issue by iainbeeston** [render-oss/terraform-provider-render#19]
I have auto deploys disabled for our project, instead I've configured our CI server to call the deploy hook for each web service after the CI build passes. At the moment we have to manually copy the deploy hook from the render dashboard into the CI service, but if the render web service resource exposed the deploy hook url then this could be automated, so that whenever a new service is added or removed the deploy hook is automatically added in our CI setup.

Could someone please expose the deploy hook url as an output for the web service resource?

**Comment by jakemalachowski** [comment]
Would using the [REST API deploy endpoint](https://api-docs.render.com/reference/create-deploy) instead of the deploy hook work for this use case?

**Comment by iainbeeston** [comment]
@jakemalachowski Yes that's true, I could use that instead, thanks for the suggestion
