### ISSUE TITLE
Postgres service is not updated to match the new versions

### ISSUE THREAD

**Issue by ahmadabdelhalim** [render-oss/terraform-provider-render#35]
Hello,

I can't create a Postgres service because the provider only supports legacy versions, not the latest ones. The new version also has a storage parameter for customization, which is missing as well.

![CleanShot 2024-11-09 at 19 38 32](https://github.com/user-attachments/assets/b483bc86-4a72-4016-ac4d-783e7110e52e)

**Comment by jakemalachowski** [comment]
New Postgres plan support has been added in v1.3.4
